# Generated by Django 5.0.3 on 2024-04-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
