# Generated by Django 5.0.3 on 2024-04-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_register_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
