# Generated by Django 5.0.3 on 2024-04-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_register_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('f_rating', models.CharField(max_length=255)),
                ('a_rating', models.CharField(max_length=255)),
                ('f_availability', models.CharField(max_length=255)),
                ('a_availability', models.CharField(max_length=255)),
                ('a_image_url', models.URLField()),
                ('f_product', models.URLField()),
                ('a_product', models.URLField()),
            ],
        ),
    ]
